namespace PataRoad.Core.Items
{
    /// <summary>
    /// Interface of ANY item.
    /// </summary>
    public interface IItem
    {
        /// <summary>
        /// Unique instance id IN SCENE, automatically generated by loader. DON'T USE this as saved data reference.
        /// </summary>
        public System.Guid Id { get; }
        /// <summary>
        /// Name of the item.
        /// </summary>
        public string Name { get; }
        /// <summary>
        /// Description of the item. Will be shown on inventory window.
        /// </summary>
        public string Description { get; }
        /// <summary>
        /// Image, that will be shown in every thumbnail.
        /// </summary>
        public UnityEngine.Sprite Image { get; }
        /// <summary>
        /// Item type, like weapon or material.
        /// </summary>
        public ItemType ItemType { get; }
    }
}
